services:
  app-amor-abigail:
    image: app-amor-abigail
    build: .
    ports:
      - "3003:3003"  # Cambi√© el puerto 3000 a 3002 en el host
    networks:
      - red-external-network
    restart: always

networks:
  red-external-network:
    external: true
